### PR TITLE
Add PTZ Service and Relay Support (and Mac RTSP server)

### PR DESCRIPTION
**Pull request by RogerHardiman**
I have implemented the PTZ service and the "Continuous Move" mode where the CCTV software sends "left, right, up, down, zoom in and zoom out commands".
On receiving these commands a callback is fired and this can be customised to drive Pan, Tilt and Zoom motors.

The Pi has a wide range of motor controller boards and motor control projects so this is the foundation for mounting the Pi Camera (or the whole Pi) on a Pan/Tilt unit.

Also included a change so WS-Discovery is not started on Windows

### CODE REVIEW

**Comment by BreeeZe** [comment]
That's pretty awesome, I can have a look at it in about two weeks, I don't have access to my regular computer right now, but it sounds promising :)

**Comment by RogerHardiman** [comment]
I will look forward to hearing from you in a few weeks.
I expect you may want to polish off the Typescript code in a few places 
(adding Types and Definitions etc). That is fine.

I've now finished my first use of this new PTZ code.
There are several USB Missile Launchers you can buy (with NodeJS drivers).
I have a Tenx USB Missile Launcher that fires 3 foam rockets. I wrote 
the NodeJS library for it recently.
You can also get USB Missile Lauchers from Dream Cheeky.

So I fixed my Raspberry Pi to the side of the Missile Launcher.
The camera view was looking along the length of the missiles.

 From some CCVTV software I can view the live video from the Missile 
Launcher.
I can Pan and Tilt the Missile Launcher and I can fire the Rockets using 
a GotoPreset command.

It is really cool.

My next use will be for the Pi to convert ONVIF Pan/Tilt/Zoom commands 
into industry standard Pelco D Pan/Tilt/Zoom commands and turn the Pi 
into a cheap IP Encoder codec that can stream video and control analogue 
PTZ cameras that support Pelco D

**Comment by RogerHardiman** [comment]
Photo of my Raspberry Pi with camera (camera is inside the case) controlling a USB Missile Launcher.
Pan, Tilt and fire Control is via ONVIF from any ONVIF compatible CCTV viewing software

pi_missile20160727_175526

**Comment by RogerHardiman** [comment]
Pull request also includes a fix in WS-Discovery to make it work on the Mac (OS X). I test my NodeJS code on Linux, Mac and Windows where possible

**Comment by RogerHardiman** [comment]
Pull now includes a config file for 'ffserver' (part of the 'ffmpeg' tools) to capture from the Mac's webcam and stream video via RTSP in H264 format.
Tested with ONVIFed on Android and Ben Software Security Spy on a Mac
Latency is huge - there may be ways to tune this but the purpose was to generate any form of RTSP video.
Currently you have to start ffserver -f ffserver_mac.conf manually.
Later commits are likely to add this as a new 'spawn' command to do this automatically with some changes to lib/utils.js to detect the different operating systems.

**Comment by RogerHardiman** [comment]
Also added ONVIF Relay support that calls the PTZ callback.
Tested with ODM.

**Comment by BreeeZe** [comment]
You've been quite busy I see :)
I'll be home again this weekend, I hope I have some time too so I can have a look.

Let's see if I can order one of those missle launchers too :)

**Comment by RogerHardiman** [comment]
There are also two Pi Pan/Tilt kits for the Pi.
Not tried either (one from Adafruit, one from OpenElectrons) but both should be easy to hook into the PTZ callback.

**Comment by RogerHardiman** [comment]
There is a company called Lingodigit that has their own ONVIF library and have written a Linux version of ONVIF Device Manager (ODM) which they call ONVIF Device Tool (ODT).
I have tested V15.12 of ODT. It needed SetSystemDateAndTime to return OK and it also needed an Events XAddr (which I think is mandatory and we should have had this already) and needed a proper GetNetworkInterfaces.
ODT 15.12 does crash every now and then so is not 100% stable and also seems to have a bug in its PTZ speed control.
But it is a good tool and runs on Linux (I use it in Virtual Box).

**Comment by RogerHardiman** [comment]
Implements the fix from RPOS problem report #30

**Pull request merged**
