### PR TITLE
Enhance ONVIF compatibility

### PR DESCRIPTION
**Pull request by RogerHardiman**
I have made changes which improve ONVIF compatibility. There is support for two more SOAP Messages. There is also bug fixes for some existing SOAP messages where the XML had errors.
I also found a bug in your sparse array lookup code.

With these changes ONVIF Device Manager can now connect to the Raspberry Pi and receive a list of profiles and stream the RTSP video

I also had to make a change to the SOAP package to add SOAP 1.2 (2003) envelopes.
I have not looked to see if we can move the whole project onto a formal release of Node-Soap
I have just used your hacked version and added a small change too.

I have changed the .ts files but have not committed any .js file changes.
I have not been able to make VS recreate all the .js files automatically so was testing by running tsc from the command line on Windows or on the Pi

### CODE REVIEW

**Comment by BreeeZe** [comment]
Thanks for your changes, I have no personal use for this project any more, but I will accept changes and updates that make the code more useful for anyone who wishes to use it.

I developed the .ts using Visual Studio Code (https://code.visualstudio.com) mostly and ran tsc from the commandline too.
I think I also have a local branch which used a gulp task (http://gulpjs.com) to run some stuff which is also supported by vs code and the full vs for windows.

**Comment by RogerHardiman** [comment]
Thanks for applying the changes. You mentioned you have no use for the project any more. I may have some further changes to add. Do you want to continue to host the project?

**Comment by BreeeZe** [comment]
Yes, I still want to continue hosting the project.
Your pull requests are, off course, welcome :)
I just enabled github email notifications so I'll notice them sooner too :)

**Comment by RogerHardiman** [comment]
Hi there

/> //Yes, I still want to continue hosting the project.//
/That is good.

/> Your pull requests are, off course, welcome :)//
//
/I will have more for you. Right now I am doing WS-Discovery.
I am using xml2js with a RegEx to filter the SOAP XML namespaces as I 
know how to use that.
It would be nicer to use node-soap or the parts of it that parse the WSDL
So may want some help making the code nice rather than a bit of a hack.

I was also thinking of adding the PTZ service and controlling my USB 
Pan/Tilt USB Missile Launcher.


/> GetSnapshotUri//
/I had also noticed that you set the Capability to a False.
But Meyertech's ONVIF CCTV software (called Nano) requests it and then 
crashes as the XML was not valid.
So bugs in the Meyertech Nano software. But easier to send some valid XML

There is a Python RPi Camera Library that can take snapshots and live 
video at the same time. I was going to see how they do it.

For now I may do a Pull Request to deliver the RPi logo .jpg file you 
have if there is no JPEG in /dev/shm


Roger




On 09/05/2016 08:18, Jeroen Versteege wrote:
>
> Yes, I still want to continue hosting the project.
> Your pull requests are, off course, welcome :)
> I just enabled github email notifications so I'll notice them sooner 
> too :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/BreeeZe/rpos/pull/9#issuecomment-217792442>
>

-- 
Roger Hardiman
RJH Technical Consultancy Ltd
07968 245759
www.rjh.org.uk
roger@rjh.org.uk

**Comment by BreeeZe** [comment]
Did you have a look at my other repo : https://github.com/BreeeZe/node-soap-servicegenerator ?
It is also a bit hacked together, but I used it to generate all the call signatures and request and response objects from the wsdl files.

**Pull request merged**
