### PR TITLE
[WIP] Relative PTZ for pan-tilt-hat

### PR DESCRIPTION
**Pull request by caspermeijn**
This addes support for the relative PTZ ONVIF call. However not all drivers support this, so the ONVIF client needs to be informed about the supported translation spaces.

The current revision doesn't detect the unsupported drivers and always reports relative PTZ to be available, but the PTZ driver makes this available as a boolean. 

I don't have enough JavaScript knowledge to see the best way to only initialize the relevant translation space. Could you provide me with hints on how to do this? 

PS. I needed these changes to make this work properly: https://github.com/RogerHardiman/node-pan-tilt-hat/pull/1

Thanks,
Casper

### CODE REVIEW

**Comment by RogerHardiman** [comment]
Hi. This is great work.

I will try and take a look over the next few days.

Thanks. Roger

**Comment by RogerHardiman** [comment]
I have a quick question for you.
As a CCTV engineer I can see the benefit in Continual Pan/Tilt (it mirrors the old analogue CCTV systems) and the Absolute Pan/Tilt to go to a known position.

In what situations do you find Relative Move beneficial?

Thanks
Roger

**Comment by RogerHardiman** [comment]
I added some additional code to check if PTZ Driver supports Relative PTZ and then changes the SOAP replies (that was the one item on your ToDo list)

I have made a few changes to the PTZ code (your code and my code) after validating with SoapUI and Test Tool ver 14.

But I cannot get ONVIF Device Manager to control Absolute or Relative PTZ.
I'm sure it does it (and I have done it with other ONVIF cameras)

Have you tried ONVIF Device Manage with your changes?

**Comment by RogerHardiman** [comment]
Got ONVIF Device Manager working - I did not use the right PTZ Configuration details in the Media Service GetProfile.

**Comment by caspermeijn** [comment]
Thanks for completing the work!

I develop [ONVIFViewer](https://gitlab.com/caspermeijn/onvifviewer), an simple application for viewing cameras. Think of it as the nanny cam usecase, then you need to move around to center an object in the picture. This is where I use the relative move for.

I have not used ONVIF Device Manager for my testing, only ONVIFViewer.

The absolute position looks great, that would have been my next pull request ;-) However, ONVIFViewer doesn't support it yet, so I can't test that right now.

I noticed that ONVIFViewer is unable to detect that relative move is unavailable for the other PTZ drivers. I will check the spec to see which fields need to be removed from the PTZ service replies and create another commit if needed.

**Pull request merged**
